// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
using System.Diagnostics;
using System.Text;

namespace NarrativeTrace.Glossary;

/// <summary>
/// Renders the generated <c>glossary.md</c> view from a
/// <see cref="Glossary"/>.
/// </summary>
/// <remarks>
/// The Markdown view is the PR-review surface (ADR-011): one section per
/// context, one table per term kind, definitions/synonyms/translations
/// inline. It is regenerated on every harvest; the JSON is the single
/// editable source. Accepted abbreviations lead the document when the project
/// declares any — the review surface must show the vocabulary decisions it
/// exists to show, and shorthand is the one kind that is not a term.
/// </remarks>
public static class GlossaryMarkdownRenderer
{
    private const string AbbreviationTableHeader =
        "| Abbreviation | Expands to |\n|---|---|\n";

    private const string TableHeader =
        "| Term | Status | Definition | Deprecated synonyms | Translations |\n"
        + "|---|---|---|---|---|\n";

    /// <summary>Renders the full Markdown document.</summary>
    /// <param name="glossary">Glossary to render; must not be null.</param>
    /// <returns>
    /// Markdown text ending in a newline; contexts sorted by name, one table
    /// per kind present.
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="glossary"/> is null.</exception>
    public static string Render(Glossary glossary)
    {
        if (glossary is null)
        {
            throw new ArgumentNullException(nameof(glossary));
        }

        var output = new StringBuilder();
        output.Append("# Domain Glossary\n\n");
        output.Append(
            "Generated from `glossary.json` — edit the JSON, then regenerate;"
            + " do not edit this file.\n");
        RenderAbbreviations(output, glossary.Abbreviations);
        foreach (var name in glossary.Contexts.Keys.OrderBy(n => n, StringComparer.Ordinal))
        {
            RenderContext(output, glossary, glossary.Contexts[name]);
        }

        Debug.Assert(output[output.Length - 1] == '\n', "document must end with a newline");
        return output.ToString();
    }

    private static void RenderAbbreviations(
        StringBuilder output, IReadOnlyDictionary<string, string> abbreviations)
    {
        if (abbreviations.Count == 0)
        {
            return;
        }

        output.Append("\n## Accepted abbreviations\n\n").Append(AbbreviationTableHeader);
        foreach (var token in abbreviations.Keys.OrderBy(t => t, StringComparer.Ordinal))
        {
            output.Append("| `").Append(Cell(token)).Append("` | ")
                .Append(Cell(abbreviations[token])).Append(" |\n");
        }
    }

    private static void RenderContext(
        StringBuilder output, Glossary glossary, BoundedContext context)
    {
        output.Append("\n## ").Append(Cell(context.Name)).Append('\n');
        if (context.Description is not null)
        {
            output.Append('\n').Append(context.Description).Append('\n');
        }

        if (context.Packages.Count > 0)
        {
            output.Append("\nPackages: ")
                .Append(string.Join(", ", context.Packages.Select(p => $"`{p}`")))
                .Append('\n');
        }

        foreach (TermKind kind in Enum.GetValues(typeof(TermKind)))
        {
            RenderKindTable(output, TermsOf(glossary, context.Name, kind), kind);
        }
    }

    private static void RenderKindTable(
        StringBuilder output, IReadOnlyList<GlossaryTerm> terms, TermKind kind)
    {
        if (terms.Count == 0)
        {
            return;
        }

        output.Append("\n### ").Append(Heading(kind)).Append("\n\n").Append(TableHeader);
        foreach (var term in terms)
        {
            RenderRow(output, term);
        }
    }

    private static void RenderRow(StringBuilder output, GlossaryTerm term)
    {
        output.Append("| ").Append(Cell(term.Term))
            .Append(" | ").Append(term.Status.JsonName())
            .Append(" | ").Append(term.Definition is null ? "" : Cell(term.Definition))
            .Append(" | ").Append(SynonymsCell(term))
            .Append(" | ").Append(TranslationsCell(term))
            .Append(" |\n");
    }

    private static List<GlossaryTerm> TermsOf(
        Glossary glossary, string context, TermKind kind)
    {
        return glossary.Terms
            .Where(term => term.Context == context && term.Kind == kind)
            .ToList();
    }

    private static string Heading(TermKind kind)
    {
        return kind switch
        {
            TermKind.Word => "Words",
            TermKind.NounPhrase => "Noun phrases",
            TermKind.VerbPhrase => "Verb phrases",
            TermKind.Template => "Templates",
            _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, null),
        };
    }

    private static string SynonymsCell(GlossaryTerm term)
    {
        return string.Join("; ", term.Synonyms.Select(
            s => s.Note is null ? Cell(s.Alias) : $"{Cell(s.Alias)} — {Cell(s.Note)}"));
    }

    private static string TranslationsCell(GlossaryTerm term)
    {
        return string.Join("; ", term.Translations.Keys
            .OrderBy(locale => locale, StringComparer.Ordinal)
            .Select(locale => $"{Cell(locale)}: {Cell(term.Translations[locale])}"));
    }

    /// <summary>Escapes table-breaking characters: pipes are escaped, newlines collapse to spaces.</summary>
    private static string Cell(string text)
    {
        return text.Replace("|", "\\|").Replace("\r\n", " ")
            .Replace('\n', ' ').Replace('\r', ' ');
    }
}
