<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NarrativeTrace.Diagrams.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../NarrativeTrace.Core/NarrativeTrace.Core.csproj" />
  </ItemGroup>
</Project>
