// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
using NarrativeTrace.Glossary;
using Xunit;

namespace NarrativeTrace.Glossary.Tests;

public class GlossaryMarkdownRendererTests
{
    private static readonly DateTime FirstSeen = new(2026, 8, 11, 0, 0, 0, DateTimeKind.Utc);

    [Fact]
    public void Renders_header_only_for_empty_glossary()
    {
        var markdown = GlossaryMarkdownRenderer.Render(
            new Glossary(1, new Dictionary<string, BoundedContext>(), []));

        Assert.Equal(
            "# Domain Glossary\n\n"
            + "Generated from `glossary.json` — edit the JSON, then regenerate;"
            + " do not edit this file.\n",
            markdown);
    }

    [Fact]
    public void Renders_the_accepted_abbreviations_before_the_contexts()
    {
        var glossary = new Glossary(
            2,
            new Dictionary<string, BoundedContext> { ["billing"] = new("billing", []) },
            [Term("charge", "billing", TermKind.Word)],
            new Dictionary<string, string> { ["fx"] = "foreign exchange", ["calc"] = "calculate" });

        var markdown = GlossaryMarkdownRenderer.Render(glossary);

        Assert.Contains(
            "\n## Accepted abbreviations\n\n"
            + "| Abbreviation | Expands to |\n|---|---|\n"
            + "| `calc` | calculate |\n"
            + "| `fx` | foreign exchange |\n",
            markdown,
            StringComparison.Ordinal);
        Assert.InRange(
            markdown.IndexOf("## Accepted abbreviations", StringComparison.Ordinal),
            0,
            markdown.IndexOf("## billing", StringComparison.Ordinal));
    }

    [Fact]
    public void Omits_the_abbreviations_section_when_none_are_declared()
    {
        var glossary = new Glossary(
            1,
            new Dictionary<string, BoundedContext> { ["billing"] = new("billing", []) },
            [Term("charge", "billing", TermKind.Word)]);

        var markdown = GlossaryMarkdownRenderer.Render(glossary);

        Assert.DoesNotContain("Accepted abbreviations", markdown, StringComparison.Ordinal);
    }

    [Fact]
    public void Renders_contexts_sorted_with_description_packages_and_kind_tables()
    {
        var glossary = new Glossary(
            1,
            new Dictionary<string, BoundedContext>
            {
                ["sales"] = new("sales", []),
                ["billing"] = new(
                    "billing", ["Acme.Billing", "Acme.Funds"], "Money things."),
            },
            [
                Term("overdraft account", "billing", TermKind.NounPhrase),
                Term("charge", "billing", TermKind.Word),
                Term("place order", "sales", TermKind.VerbPhrase),
            ]);

        var markdown = GlossaryMarkdownRenderer.Render(glossary);

        var billingAt = markdown.IndexOf("## billing", StringComparison.Ordinal);
        var salesAt = markdown.IndexOf("## sales", StringComparison.Ordinal);
        Assert.InRange(billingAt, 0, salesAt);
        Assert.Contains("\nMoney things.\n", markdown, StringComparison.Ordinal);
        Assert.Contains(
            "Packages: `Acme.Billing`, `Acme.Funds`", markdown, StringComparison.Ordinal);
        Assert.Contains("### Words", markdown, StringComparison.Ordinal);
        Assert.Contains("### Noun phrases", markdown, StringComparison.Ordinal);
        Assert.Contains("### Verb phrases", markdown, StringComparison.Ordinal);
        Assert.DoesNotContain("### Templates", markdown, StringComparison.Ordinal);
        Assert.EndsWith("\n", markdown, StringComparison.Ordinal);
    }

    [Fact]
    public void Renders_term_rows_with_definition_synonyms_and_translations()
    {
        var glossary = OneTermGlossary(new GlossaryTerm(
            "overdraft account", "billing", TermKind.NounPhrase, TermStatus.Curated,
            "Account below zero.",
            new Dictionary<string, string> { ["fr"] = "compte", ["es"] = "cuenta" },
            [new SynonymAlias("account with overdraft", "legacy"), new SynonymAlias("odac")],
            [], FirstSeen));

        var markdown = GlossaryMarkdownRenderer.Render(glossary);

        Assert.Contains(
            "| overdraft account | curated | Account below zero. "
            + "| account with overdraft — legacy; odac "
            + "| es: cuenta; fr: compte |",
            markdown,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Escapes_pipes_and_collapses_newlines_in_cells()
    {
        var glossary = OneTermGlossary(new GlossaryTerm(
            "charge", "billing", TermKind.Word, TermStatus.Curated,
            "a|b\r\nc\nd\re", new Dictionary<string, string>(), [], [], FirstSeen));

        Assert.Contains(
            "| charge | curated | a\\|b c d e |",
            GlossaryMarkdownRenderer.Render(glossary),
            StringComparison.Ordinal);
    }

    [Fact]
    public void Rejects_null_glossary()
    {
        Assert.Throws<ArgumentNullException>(() => GlossaryMarkdownRenderer.Render(null!));
    }

    private static Glossary OneTermGlossary(GlossaryTerm term)
    {
        return new Glossary(
            1,
            new Dictionary<string, BoundedContext> { ["billing"] = new("billing", []) },
            [term]);
    }

    private static GlossaryTerm Term(string term, string context, TermKind kind)
    {
        return new GlossaryTerm(
            term, context, kind, TermStatus.Harvested,
            null, new Dictionary<string, string>(), [], [], FirstSeen);
    }
}
